@BASE_URL = http://localhost:5242
@USER_ID = 1

###
GET {{BASE_URL}}/
Accept: application/json
Authorization: Bearer 123456789

### 
GET {{BASE_URL}}/api/user
Accept: application/json
Authorization: Bearer 123456789
###
GET {{BASE_URL}}/api/user/{{USER_ID}}
Accept: application/json
Authorization: Bearer 123456789
###
GET {{BASE_URL}}/api/employee/{{USER_ID}}
Accept: application/json
Authorization: Bearer 123456789
###
GET {{BASE_URL}}/api/user/999
Accept: application/json
Authorization: Bearer 123456789
###
POST {{BASE_URL}}/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer 123456789

{
  "firstName": "Piotr",
  "lastName": "Zielinski",
  "email": "piotr.zielitnski@example.com"
}

###
PUT {{BASE_URL}}/api/user/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 123456789

{
  "firstName": "Jan-Updated",
  "lastName": "Kowalski-Updated",
  "email": "jan.updated@example.com"
}

###
PUT {{BASE_URL}}/api/user/999
Content-Type: application/json
Accept: application/json
Authorization: Bearer 123456789

{
  "firstName": "Ghost",
  "lastName": "User",
  "email": "ghost@example.com"
}

###
DELETE {{BASE_URL}}/api/user/2
Accept: application/json
Authorization: Bearer 123456789
###
DELETE {{BASE_URL}}/api/user/999
Accept: application/json
Authorization: Bearer 123456789
###
GET {{BASE_URL}}/api/user
Accept: application/json
Authorization: Bearer 123456789